CREATE DATABASE AWS_COURSE_DB;

CREATE TABLE AWS_COURSE_TABLE_01 (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100)
);

INSERT INTO AWS_COURSE_TABLE_01 VALUES (1, "Konst");
INSERT INTO AWS_COURSE_TABLE_01 VALUES (1, "Serg");

SELECT * FROM AWS_COURSE_TABLE_01;
